### ISSUE TITLE
"dead" needs refining

### ISSUE THREAD

**Issue by jamiebuilds** [browserslist/browserslist#250]
> `dead`: browsers from last 2 version query, but with less than 0.5% in global usage statistics and without official support or updates for 24 months. Right now it is IE 10, IE_Mob 10, BlackBerry 10, and BlackBerry 7.

Even with `not dead`, browsers like:

- QQ Browser 1.2 (0% market share)
- Android Browser 62 (0% market share)
- Baidu Browser 7.12 (0% market share)
- Opera Mobile 12.1 (0% market share)
- Opera Mobile 37 (0.01% market share)
- Opera 49 (0.02% market share)
- etc

I think that the AND condition is the problem.

- It's good because it means a version of chrome released 1 hour ago with less than 0.5% usage isn't considered "dead"
- It's bad because a browser that was released less than 2 years ago but has 0 users isn't considered "dead"

Alternatives:

- "deadness" score
- "dead" is determined by age exceeding market share

**Comment by ai** [comment]
You are think very exclusively 😏

QQ browser has a huge user market in China. Android browser and Opera Mini had a huge market in poor countries.

Removing this browsers from default browsers list (default has `not dead`) will make website accessible only for rich people from Western countries.

**Comment by jamiebuilds** [comment]
From region specific metrics that I see, QQ Browser has less than 0.1% of the asian market, and only 2% in China.

**Comment by jamiebuilds** [comment]
Regardless, you're cherry picking and ignoring the logical issue

**Comment by ai** [comment]
2 rich guys from US with latest smartphones speaking about browsers in rest of the world :D.

Let’s collect opinions from other people:

* @yisibl @gucong3000 should we remove QQ Browsers? Is it non-popular in China?
* @pepelsbey @mathiasbynens should we remove all Opera Mini from default Browserslist query?
* @ireade @unicodeveloper can you give some feedback about browsers in Africa?

Whom should we ask about browses in India?

**Comment by ai** [comment]
> Regardless, you're cherry picking and ignoring the logical issue

We use the same logic. The value is different. You try to reduce bundle size by removing unpopular (by your opinion) browsers. I try to force browsers diversity by adding local (in my opinion) browsers.

Because Browserslist is a community project we need to found a compromise between our values. First, let’s remove `in out opinion` part.

Let’s me explain my values. Opera was very popular in Russia. But not in US and Western Europe. So developers just ignored (especially when we start to have prefixes problem). Like why I should take care of the strange browser in some unknown cold country sine Opera global popularity was small. The same thing with a Linux. A lot of developers still don’t care about since it’s global popularity is about few %.

And this is an incredibly bad experience. But also it is very bad for everyone in long-term. All “sticking with IE” problems in the past we had only because developers support only popular browser (IE) and users use only browsers where all sites work. As result, popular IE becomes more popular and rest browsers died.

And we have the same problem right now with Chrome. If we will take care only about Firefox, Chrome, Safari, and Edge, it will kill all browsers innovations. But also it will make Web uncomfortable for other users outside of rich Western world with fast Internet and powerful smartphones.

So browsers diversity was one of the reasons why I created Autoprefixer. To stop ignoring other browsers in vendor prefixes. So Browserslist will always take care of browsers diversity.

But, of course, I am open to suggestions. We can remove browsers, which are unsafe for users (this is why `dead` contains browsers without security updates) to make Web safer place. Also, I can remove browsers if reallly nobody use it around the globe.

**Comment by pepelsbey** [comment]
None of us with @mathiasbynens is currently working at Opera, so we don’t have any insider story. I’d maybe ask @tkadlec, he gave a nice talk on proxy browsers a few years ago.

**Comment by pepelsbey** [comment]
You can also find some Russian stats in Yandex Radar, see [Browsers in Russia: All mobile devices](https://radar.metrika.yandex/browsers?device-category=5) filter: Android Browser 8.71%, for example.

**Comment by jan-dh** [comment]
I think if you want to cherry pick based on your own location there's already the possibility to do so using browserlist in combination with your country data. Seems flexible enough to limit your browsers.

```
> .05% in BE
```

**Comment by gucong3000** [comment]
> should we remove QQ Browsers? Is it non-popular in China?

[From January 1, 2018 to March 31, 2018, about 6.36% of Chinese users use QQ Browser. ](http://tongji.baidu.com/data/browser/)

**Comment by unicodeveloper** [comment]
> @ireade @unicodeveloper can you give some feedback about browsers in Africa?

Opera Mini is still very active in Africa. UC Browser too.

**Comment by ai** [comment]
cc @itchina110

**Comment by ai** [comment]
@unicodeveloper sorry, I hate this question too. But could you provide some reason. Like there is % of users. Of important African company care about this these users. Or like personal story, like I see Opera Mini users everyday in public transport.

Sorry, for question, but you saw that I must to fight against Western developers with Blink-only browsers. I need some sources for fight.

**Comment by unicodeveloper** [comment]
@ai Personally, I see people use Opera Mini everyday here. In the streets, in cafes, in buses, everywhere you can think of. That's not enough stats though. I just contacted one of my friend that works at Opera to pull up the percentage for me. I'll update this thread once I have the info.

**Comment by unicodeveloper** [comment]
@ai I just got the info:

* 100M - Africa
* 25M - Nigeria alone

That's several millions of users still actively using Opera Mini. 😄

**Comment by ai** [comment]
@itchina110 hi, we need some Chinese developers community thoughts about this question about Autoprefixer/babel default browsers. Should we remove QQ and Baidu browser from defaults?

**Comment by gucong3000** [comment]
Most Chinese browsers are dual-core: Blink & IE, They are based on Chromium. js run on `v8`,

With only two exceptions, Maxthon and UC

Maxthon are dual-core too, but use Webkit & IE, It is use `JavaScriptCore` to run js, It can be handled as safari.

UC is a monster, It renders the page on the server, just like Opera mini

**Comment by ai** [comment]
@gucong3000 awesome, thanks. This dual core can affect statistics (counters could see a “Chrome” when it is some local browser).

What can you say about QQ vs Baidu vs UC vs Maxthon local market? Both the real statistics and every-day experience is acceptable.

**Comment by gucong3000** [comment]
> counters could see a “Chrome” when it is some local browse

360 browser is not tagged in `userAgnet`, other browsers have their own identifier in `userAgnet`, statistics will be different from Chrome


> What can you say about QQ vs Baidu vs UC vs Maxthon local market?

In addition to UC, other browser vendors just modified the UI and packaged Chromium (Except Maxthon
, It is Webkit) with some custom plug-ins, not real browsers, just like Opera 15+.

**Comment by gucong3000** [comment]
I usually configure this way: `Chrome >= 30`, this configuration is fully compatible with Opera 15+ QQ browser, Maxthon, but this is not intuitive for beginners

**Comment by ai** [comment]
I added Opera 12.1 to `dead` browsers

**Comment by ai** [comment]
Opera Mobile, Opera Mini, Baidu, QQ stays since they are important in some regions.

I will change my mind if:

* There will not be security updates
* Local community leaders say that it is not important to track these browsers anymore
* Somebody presents good reasons why removing these browsers will be good for Web ecosystem in long-term

**Comment by toxic-johann** [comment]
Hello, @ai . @itchina110 ask me to reply the post for him.

In China, the browser situation is slightly different.

In PC, browser like QQ browser, UC browser, 360 browser and so on have two engines. One of them is chromium, and the other is IE in mostly.

In mobile, most of the browser in China are based on Chromium. Thought some of them is based on an very old version chrome.

But we still have some browser like UC mini, which support two engine in mobile.

**Comment by tkadlec** [comment]
Just chiming in since I was tagged—this is a fascinating thread with a lot going on. I see you're getting input directly from folks in markets where UC and Opera Mini (among others) are popular so I'll hang back and let them do the talking. :)

Let me know though if there's something specific I can help with.

**Comment by tkadlec** [comment]
@ai I haven't seen it officially deprecated—but I may have missed it.

The only caution I would give there is that the 12.x releases are the last releases to work on S60 phones, as well as any Android version prior to 4.x.

I haven't seen anything to suggest the market share for either is significant enough to warrant it being in the default list, but would suggest someone verify.

**Comment by edmorley** [comment]
> and without official support or updates for 24 months

24 months seems like too large a time window without updates to consider a product secure. What do people think about reducing that to 12 months? (Or even less; presuming that the dates used for the calculation include security updates and not just major releases.)

**Comment by ai** [comment]
@edmorley good point. We can even change it to “if there were no security patches for a critical issue for 6 months”.

Anyway, right now it is not a law. It depends on a discussion. So if you have an example we can consider it.

**Comment by ylemkimon** [comment]
I agree about their importance, as I myself live in South Korea, where IE usage is very high, due to non-standard components using ActiveX.

But Baidu Browser (`baidu`) and QQ Browser (`and_qq`) in caniuse data seem to be mobile browsers, where the discussion seems to be mainly based on PC browsers. And I can't seem to find what browsers do Baidu Browser 1.2 and QQ Browser 7.12, which are only versions provided by caniuse, refer to. (https://github.com/Fyrd/caniuse/issues/4463)

I think we should add (local-)popular PC browsers, and remove above browsers if it is no longer used.
