### ISSUE TITLE
Allow > and >= for node

### ISSUE THREAD

**Issue by jaydenseric** [browserslist/browserslist#293]
Using a query like this:

```
node >= 10
```

<img width="286" alt="screen shot 2018-09-10 at 2 20 09 pm" src="https://user-images.githubusercontent.com/1754873/45276341-f766b480-b504-11e8-8ab2-9dcbd07e9505.png">

Results in an error like this:

```
browserslist: Unknown browser node
```

<img width="237" alt="screen shot 2018-09-10 at 2 20 21 pm" src="https://user-images.githubusercontent.com/1754873/45276334-e61da800-b504-11e8-8bee-da9df1e1736b.png">

A query like this works, but it seems that it means supporting _only_ that exact version:

```
node 10
```

**Comment by ai** [comment]
Sure, good idea.

Do you want to send PR?

**Comment by steven87vt** [comment]
Just wanted to toss this out there, being able to specify a minimum node range would be super helpful on my project just because it seems most team members are on different versions. The main reason for us would be to set the babel-env#targets config to a browserslist query `node > 9.5.0` when `BABEL_ENV=test` and let the jest tests run babel'ed against the current users node version.

**Comment by ai** [comment]
@steven87vt do you want to send PR?

**Comment by ai** [comment]
Released in 4.5.
