### ISSUE TITLE
Internal: Replace electron-to-chromium with electron-release

### ISSUE THREAD

**Issue by mutech** [browserslist/browserslist#328]
Following a discussion in #326, I'm proposing to replace electron-to-chromium with electron-release.

Advantages:
* Maintained by electron team
* More information (e.g. Node version)

**Comment by ai** [comment]
Great idea. Do you want to send PR?

**Comment by Kilian** [comment]
Hi, I'm both the maintainer of `electron-to-chromium` and part of the electron governance team. 

I can add a node-versions.js to `electron-to-chromium` for you to consume, that'll be substantially lighter than using `electron-releases`. I got this request before: https://github.com/Kilian/electron-to-chromium/issues/17 but I wasn't sure about its use cases. 

I'm still not sure, because the node and the chrome part of a given electron release share their V8 and so their javascript support with the only difference being internal API's, but if it's useful for browserslist consumers then that shouldn't be too hard to add.

**Comment by ai** [comment]
We don’t need Node.js version right now
