### ISSUE TITLE
Support for polyfill-library

### ISSUE THREAD

**Issue by gbiorczyk** [browserslist/browserslist#357]
Hi,

I would like to write a code that allows me to automatically add all mixins for the browsers given in package.json.

Here's the part of the code in package.json:
```
"browserslist": [
  "last 3 versions"
],
```

I have something like this in the webpack file:
```
const browserslist = require('browserslist');
const list = browserslist();
console.log(list);
```

I get the following list of browsers:
```
[
'and_chr 71',
'and_ff 64',
'and_qq 1.2',
'and_uc 11.8',
'android 67',
'android 4.4.3-4.4.4',
'android 4.4',
'baidu 7.12',
'bb 10',
'bb 7',
'chrome 72',
'chrome 71',
'chrome 70',
'edge 18',
'edge 17',
'edge 16',
'firefox 65',
'firefox 64',
'firefox 63',
'ie 11',
'ie 10',
'ie 9',
'ie_mob 11',
'ie_mob 10',
'ios_saf 12.0-12.1',
'ios_saf 11.3-11.4',
'ios_saf 11.0-11.2',
'op_mini all',
'op_mob 46',
'op_mob 12.1',
'op_mob 12',
'opera 58',
'opera 57',
'opera 56',
'safari 12',
'safari 11.1',
'safari 11',
'samsung 8.2',
'samsung 7.2-7.4',
'samsung 6.2-6.4'
]
```

Here I found a list of all mixins and in each there is a file with a list of browsers for which it is required:
https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/CustomEvent/config.json

How can I check if the list of my browsers is in the scope of this from the config.js file?

**Comment by ai** [comment]
> How can I check if the list of my browsers is in the scope of this from the config.js file?

They have a custom syntax for ranges (`"edge_mob": "<14"`, `"ie_mob": "10 - *"`). I am not sure what is this syntax and can you find a parser. Maybe you will need to write a parser on your own.

You should ask `polyfill-library` author. Maybe they can give you a parser.

I am closing this issue because supporting this config is out of Browserslist purpose. It should be in independent npm package or in `polyfill-library`.
