### ISSUE TITLE
Q: Why not just support 100% of browsers?

### ISSUE THREAD

**Issue by meirroth** [browserslist/browserslist#465]
lets say I have a small website with a small style sheet, adding support to 100% of browsers wont add a significant file size difference. (I did not test this)
So my question is: is there another reason why to not support all browsers besides the file size issue?
thanks.

**Comment by ai** [comment]
> lets say I have a small website with a small style sheet, adding support to 100% of browsers wont add a significant file size difference. (I did not test this)

Test it. Look at numbers before gzip, because this metric is more accurate of how long the browser will compile your CSS and JS.

Babel will show a significant performance drop because `babel-preset-env` will insert a lot of polyfills.

It’s not so dramatic size grow in Autoprefixer or `postcss-preset-env`, but it will still affect CSS parsing time.
