### ISSUE TITLE
Use selectors for supported TLS-versions

### ISSUE THREAD

**Issue by dilyanpalauzov** [browserslist/browserslist#473]
Since servers move towards disabling TLS 1.0, add security-related selectors to browserslist:
* NO tls_11 - exclude broswers not supporting TLS 1.1, not supporting TLS 1.2 and not supporting TLS 1.3 (or something like this).

The TLS support can be taken from [testssl.sh](https://testssl.sh/) or [SSL Test](https://www.ssllabs.com/ssltest/).

**Comment by ai** [comment]
Sorry, I do not want feature-based queries in Browserslist, because it will be very hard to add.

But I know a better way for you. You can create a script that will convert [`caniuse-api`](https://www.npmjs.com/package/caniuse-api) to Browserslist config with exact browser versions. Then you can put them to [Sharable Config](https://github.com/browserslist/browserslist#shareable-configs) and publish it to npm. You can create the GitHub Actions script to update the config and release the new npm version automatically.

If your team really want core support, you can pay us to develop this tool. [Browserslist’s OpenCollective](https://opencollective.com/browserslist) is a way to do it.
