### ISSUE TITLE
Unknown browser query `and_qq undefined`. Maybe you are using old Browserslist or made typo in query.

### ISSUE THREAD

**Issue by sai-sharan** [browserslist/browserslist#494]
Hi,

When trying to build my react app, I'm getting the following error:

$ react-scripts build
Creating an optimized production build...
Failed to compile.

Unknown browser query `and_qq undefined`. Maybe you are using old Browserslist or made typo in query.

error Command failed with exit code 1.

Can you please help me with this?

**Comment by ai** [comment]
It happens because somebody sends a query with `and_qq undefined` wrong string into Browserslist.

Unfortunately, it came outside of Browserslist, so I can’t be really helpful. You need to check the system around Browserslist.

What is your Browserslist config (you can check it in `package.json` → `browserslist` or in `.browserslistrc`)

**Comment by sai-sharan** [comment]
Hi Andrey, 

Thanks for your prompt reply.

My Browserlist config is:
```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by ai** [comment]
The config is OK. Sorry, I have no idea who set `and_qq undefined`. You can create an issue in Create React App.
