### ISSUE TITLE
JS API: Config cannot be object

### ISSUE THREAD

**Issue by arvigeus** [browserslist/browserslist#512]
Related: #474 

The following code throws an error:

```js
const browserslist = require("browserslist");

const browsers = browserslist({
    production: [ "defaults" ],
    development: [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version"
    ]
  }, {
    env: "production",
  });
```

Expected: load configuration for `production`.

I think `production` should be default if `env` is not passed.

**Comment by ai** [comment]
What is use case for you to not using `browserslist(config[env])` directly?

**Comment by arvigeus** [comment]
I was testing my shareable config (that object was loaded from there).
It just seems inconsistent to me, especially when there is an option for environment.

**Comment by ai** [comment]
JS API was created to be used inside the tools. API was not designed to test configs.

For instance, the first argument is not for the config, but for tool-specific override like:

```js
let browsers = browserslist(autoprefixerOps.overideBrowserslist, {
  env: autoprefixerOps.env
})
```

The best way to test sharable config:

```js
// test.js

console.log(browserslist('extends ./index.js', { dangerousExtend: true }))
```

```sh
node test.js
BROWSERSLIST_ENV=production node test.js
```

I am closing this issue, since change the purpose of API will decrease code maintability, but Browserslist is suffering from the lack of [funding and support](https://opencollective.com/browserslist).
