### ISSUE TITLE
Formal specification for syntax/grammar

### ISSUE THREAD

**Issue by tom-sherman** [browserslist/browserslist#521]
Is there a spec for browserlist query syntax?

The use case being to implement browserlist in a consistent way in other languages, for example to be included in esbuild.

**Comment by ai** [comment]
Ho, we do not have formal syntax.

Technically it is not a language, but set of patterns. https://github.com/browserslist/browserslist/blob/master/index.js#L616

Do you want to create a grammar according to this regexps?

**Comment by croraf** [comment]
@ai 

I mean it is basically impossible to understand how to make a query.

In the Readme the most common example is:
```js
[
    "last 1 version",
    "> 1%",
    "IE 10"
]
```

And nowhere is explained how to interpret this query.
At some point it says that `,` is interpreted as OR. But I guess this is only when the query is made as one string, not as an array.
When the query is done as an array the components are sometimes combined as done with OR and sometimes as done with AND. Very confusing.

**Comment by ai** [comment]
The queries in array is combined as OR. The only way to combine they with AND is:

```js
[
  "last 2 versions and >1%"
]
```

How we can improve docs to make it more clear?

**Comment by croraf** [comment]
@ai 
So all array elements are combined with OR, and the only way when they are combined as AND is the case when a query is immediately followed by the "inequality percentage" query?

What about 
```
[
    "last 1 version",
    "IE 10",
    "> 1%",
]
```

Or it is the case that the only way they are combined as AND is when "last N versions" query is immediately followed by "inequality percentage" query?

-------------
My suggestion would be: Don't allow these specific cases, make it consistent so that the elements of the array are always combined as if written with OR. This would be a breaking change though.

**Comment by ai** [comment]
```
[
    "last 1 version",
    "IE 10",
    "> 1%",
]
```

All these queries are combined with `OR`. `last 1 version OR IE 10 OR > 1%`

**Comment by croraf** [comment]
So the following 2 are always equivalent?

```
[
   "any_query1",
   "any_query2",
   "any_query3",
   "any_query4",
   ...
]
```

```
[
   "any_query1, any_query2, any_query3, any_query4, ..."
]
```

**Comment by ai** [comment]
Yes

**Comment by croraf** [comment]
OK, perhaps this can be noted in the Readme somewhere. It was not obvious to me.
