### ISSUE TITLE
Update README with `update-db` script

### ISSUE THREAD

**Issue by justinzelinsky** [browserslist/browserslist#525]
After a lot of digging around an issue with `caniuse-lite`, I found this script to run and it resolved my issue. To be honest, I'm not entirely sure why I ran into an issue with multiple versions of `caniuse-lite` and why we need to manually update the lock file so I'm wondering if someone could update the README with an explanation of why this may happen and why we need to run this script to resolve it?

Thank you!

**Comment by ai** [comment]
> if someone could update the README with an explanation of why this may happen and why we need to run this script to resolve it?

Let’s start by answering you. When I will be able to explain answers to you, we can think about adding extra text to docs.

But I will need your help as an English native speaker.

> why I ran into an issue with multiple versions of caniuse-lite

It is a core problem in npm architecture. It happens with `lodash` (a lot of modern webapps bloated by `loadash` duplicates).

Just google for `npm deduplication`.

The simple example:

1. You are adding Autoprefixer to the project. `npm` looked for the latest `caniuse-lite` version (`3.0.1`) and added it to `package-lock.json` under `autoprefixer` dependencies.
2. A year after you decided to add `babel-preset-env`. At this moment we have a new version of `canuse-lite` (`3.0.50`). `npm` took the latest version and add it to lock file under `babel-preset-env` dependencies.

Now you have lockfile like:

```
autoprefixer 8.5.3
  browserslist 4.3.9
    caniuse-lie 3.0.1
babel-preset-env
  browserslist 4.5.1
    caniuse-lite 3.0.50
```

Why `npm` can’t update `autoprefixer`’s `caniuse-lite`? Because npm promises you that dependencies from your lock-file will not be updated without explicit user’s request (`npm update`).

I personally run `npm update` every-week. But you need good dependencies update policies, which most of the teams do not have.

> why we need to manually update the lock file

The main reason is to have actual data on queries like `last 2 version` or `> 1%`. If you created your project 2 years ago and didn’t update your dependencies, `last 2 versions` will return 2 years old browsers.

Another reason is `caniuse-lite` deduplication. `update-db` will guarantee that all branches in `package-lock.json` have the same `caniuse-lite` version.

**Comment by justinzelinsky** [comment]
Thank you so much for the immediate response. Thanks for the explanation -- it seems so obvious that I should have realized that.  Unfortunately we're doing our best at my company to improve our dependency update policy so this will be something that I keep in mind.

>Just google for npm deduplication.

TIL. Thank you!

Regarding your English, it seems like you already have a great understanding :) How would you like to handle updating the README? I think it would be useful since I'm sure other engineers are seeing these messages in their logs.

**Comment by ai** [comment]
We can add `Why you need to call update-db script regularly?` (after the `Best Practices` section).

Can I ask you to send PR to `README.md`?
