### ISSUE TITLE
Category request: "supported"

### ISSUE THREAD

**Issue by luckylooke** [browserslist/browserslist#700]
Hello 👋 

First of all I would like to thank you for your energy invested in this open source, appreciated 🙏 

I know that here is "dead" and I can use "not dead"... but for me, officially not supported browsers are dead enough not to be supported by my projects too.. so why wait another 24 months to keep supporting them?
> dead: browsers without official support or updates for 24 months.

So I would like to cut off that 24-months period. I didn't find the option currently. So I suggest to create category "supported" which will include only officially supported versions of the browsers by their creators. What do you think? 🧐 

Many thanks for advices or any other support in this. 🙏 

Have a wonderful day 🙂

**Comment by ai** [comment]
> so why wait another 24 months to keep supporting them?

There is `or` in the rule: we do not need to wait for 24 month. If developer told that this version is not supported, we can add version to `dead` right now.

The problem is the lack of the list of officially supported browsers.

Only a few developers have this list. For instance, it is very hard to find support status for Chinese browsers.

We are using `updates for 24 months` rule to prove that some browser does not have any support.
